version: '3.7'

services:
  
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Fdcvq2QXte5f
    command: [ "postgres", "-c", "wal_level=logical" ]
    ports:
      - 5432:5432
    volumes: 
      - c:\notes\postgressData:/var/lib/postgresql/data